# deploy/docker-compose.prod.yml
services:
  web:
    image: ghcr.io/albear007/albear-t:latest
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
  # optional: lightweight healthcheck for nicer CI failures
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 15s
      timeout: 3s
      retries: 5